### ISSUE TITLE
Checks for interpolation methods in fuse maps

### ISSUE THREAD

**Issue by mhliu0001** [XENONnT/fuse#151]
Some maps used the `RectBivariateSpline` interpolation method (like the field dependencies map), which will create unphysical values like survival probability larger than 1 or smaller than 0. See Slack thread: https://xenonnt.slack.com/archives/C0172947DFW/p1709239338483989

We should check the interpolation methods for all maps in fuse, and decide what should be used.

**Comment by ramirezdiego** [comment]
@mhliu0001 Right now we use `RectBivariateSpline` for:
- field_dependencies_map
- field_distortion_comsol_map
and also in WFSim we used these methods  for the corresponding maps.

How easy is it for you to propagate your checks to all maps? We could then decide to go to `WeightedNearestNeighbors` for the next release.

**Comment by mhliu0001** [comment]
I think for some maps we should use `RegularGridInterpolator`, if the data is based on a regular grid. Anyway the interpolation methods seem to be messy for all maps (see [note](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenonnt:miliu:fuse_civ_interpolation) here). 

I propose to make all maps with regular bins use the `RegularGridInterpolator`, other maps should use `WeightedNearestNeighbors`. Does that make sense?
