### ISSUE TITLE
cut_by_eventid issues after the latest updates

### ISSUE THREAD

**Issue by PavelKavrigin** [XENONnT/fuse#173]
Some of my tests fail again after the recently merged PRs for `entry_stop` and `cut_by_eventid`. I am using two example G4 files:
`/scratch/midway2/pkavrigin/2024-03-20_test_fuse_cut_by/*root`

Here're the new test results:
![Screenshot from 2024-03-21 11-08-11](https://github.com/XENONnT/fuse/assets/68543201/bd764b71-d7a8-41dc-9b56-2377c8bc3de3)

Before I start debugging these problems, let's clarify again how these parameters are supposed to work. Is everything correct in this list?
- if `cut_by_eventid` is **False**, `entry_start` and `entry_stop` should not matter at all, and we should get all events in tests 0-4 and 11-15;
- this selection should work only with G4 `.root` files, not `.csv` input files (this is how it's implemented at the moment);
- if `entry_start`==10 and `entry_stop`==20, it means (eventid >= 10 and eventid <= 20). All ranges in tests 11-21 look suspicious, although it _might_ be due to the TPC events themselves (low energy and/or CIV). I will run tests with some better input files in which all TPC events are 100% valid.

**Comment by PavelKavrigin** [comment]
Here're the tests with better input:
![Screenshot from 2024-03-21 11-46-57](https://github.com/XENONnT/fuse/assets/68543201/d4801386-1b89-421e-ad1f-88add0295f7e)

So it's `entry_start <= eventid < entry_stop` which makes sense, so my last point from the previous comment is not relevant.

**Comment by ramirezdiego** [comment]
> * if `cut_by_eventid` is **False**, `entry_start` and `entry_stop` should not matter at all, and we should get all events in tests 0-4 and 11-15;

Hey @PavelKavrigin, if `cut_by_eventid` is **False**, these two args should still matter and work to select the indices between `entry_start` and `entry_stop` (which I think is nicely shown in your table).

**Comment by PavelKavrigin** [comment]
@ramirezdiego - OK, then it's fine. I will close the issue.

**Comment by ramirezdiego** [comment]
Thanks for all the checks!

**Comment by mhliu0001** [comment]
Thanks! Glad that the recent PRs have made through these checks.
