### ISSUE TITLE
Confusion of `s1_photons`

### ISSUE THREAD

**Issue by zihaoxu98** [XENONnT/fuse#204]
The `s1_photons` can be either the provides of https://github.com/XENONnT/fuse/blob/fa0fff2de324c822943d684eb2718007319e0bea/fuse/plugins/detector_physics/s1_photon_hits.py#L25 or the data kind of https://github.com/XENONnT/fuse/blob/fa0fff2de324c822943d684eb2718007319e0bea/fuse/plugins/detector_physics/s1_photon_propagation.py#L40

This causes confusion and the data kinds of them are actually different.

**Comment by HenningSE** [comment]
Ohh good catch @zihaoxu98! What about changing the dtype name of the `S1PhotonHits` plugin from `"s1_photons"` to `"s1_photon_hits"`?
