### ISSUE TITLE
Random gain model mc from online

### ISSUE THREAD

**Issue by zihaoxu98** [XENONnT/fuse#230]
Every time I request gain_model_mc by
```
plg = st.get_single_plugin('046000', 'propagated_s1_photons')
print(plg.gain_model_mc.mean())
```
I get different result. I think this is related to that we get the to_pe from online version? https://github.com/XENONnT/fuse/blob/6c36d12bd6f90ffbc58da72940bee580b7360776/fuse/plugins/detector_physics/s1_photon_propagation.py#L110

**Comment by HenningSE** [comment]
Hi @zihaoxu98, something similar was discussed a while back in a [Team A meeting](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenon1t:analysistools:240125) and on [slack](https://xenonnt.slack.com/archives/C016UJZ090B/p1706201302313219) but we did not come to a conclusion.

**Comment by HenningSE** [comment]
The linked rframe PR was merged, so I guess we can close this issue? @zihaoxu98
